from . import dm_food_checklist_template
from . import dm_food_certificate
from . import dm_food_finding
from . import dm_food_inspection
from . import dm_food_inspection_extension
from . import dm_food_inspection_grade
from . import dm_food_inspection_line
from . import dm_food_inspection_stage
from . import dm_food_violation_tag
from . import res_partner_food_profile
